import { glob, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const runtimeFiles = ["apps/mcp-server/src/version.ts"];
const usage = "Usage: npm run release -- <major.minor.patch> --channel <stable|dev> [--write|--check]";

export function parseArguments(args) {
  const [version, ...flags] = args;
  let channel, mode = "preview";
  for (let i = 0; i < flags.length; i += 1) {
    const flag = flags[i];
    if (flag === "--channel" && channel === undefined) channel = flags[++i];
    else if (["--write", "--check"].includes(flag) && mode === "preview") mode = flag.slice(2);
    else throw new Error(usage);
  }
  if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/u.test(version ?? "") || !["stable", "dev"].includes(channel)) throw new Error(usage);
  return { version, channel, mode };
}

/** Prepare every file before writing so malformed metadata fails without changes. */
export async function planRelease(directory, { version, channel }) {
  parseArguments([version, "--channel", channel]);
  const changes = [];
  const readJson = async (file) => JSON.parse(await readFile(join(directory, file), "utf8"));
  const queue = async (file, after) => {
    const before = await readFile(join(directory, file), "utf8");
    if (before !== after) changes.push({ file, before, after });
  };
  const queueJson = (file, value) => queue(file, `${JSON.stringify(value, null, 2)}\n`);
  const manifest = await readJson("package.json");
  if (!Array.isArray(manifest.workspaces) || !manifest.workspaces.length || manifest.workspaces.some((pattern) => typeof pattern !== "string")) throw new Error("Expected workspace patterns in package.json.");
  const workspaceFiles = new Set();
  for (const pattern of manifest.workspaces) {
    let found = false;
    for await (const file of glob(`${pattern}/package.json`, { cwd: directory })) {
      const path = relative(directory, resolve(directory, file));
      if (path.startsWith("..") || path.split(/[\\/]/u).includes("node_modules")) throw new Error(`Unsafe workspace path: ${file}`);
      workspaceFiles.add(path);
      found = true;
    }
    if (!found) throw new Error(`No workspace manifests found for ${pattern}.`);
  }
  const lock = await readJson("package-lock.json");
  if (lock.lockfileVersion !== 3 || !lock.packages?.[""]) throw new Error("Expected an npm v3 lockfile with a root package.");
  const packageFiles = ["package.json", ...[...workspaceFiles].sort()];
  const workspaceKeys = new Set(packageFiles.map((file) => file === "package.json" ? "" : dirname(file).replaceAll("\\", "/")));
  for (const key of Object.keys(lock.packages)) {
    if (key && !key.split("/").includes("node_modules") && !workspaceKeys.has(key)) throw new Error(`Unexpected workspace in lockfile: ${key}`);
  }
  for (const file of packageFiles) {
    const value = file === "package.json" ? manifest : await readJson(file);
    const key = file === "package.json" ? "" : dirname(file).replaceAll("\\", "/");
    if (!lock.packages[key] || lock.packages[key].name !== value.name) throw new Error(`Missing or mismatched lockfile package: ${file}`);
    value.version = version;
    lock.packages[key].version = version;
    await queueJson(file, value);
  }
  lock.version = version;
  await queueJson("package-lock.json", lock);
  const displayName = channel === "stable" ? "Recipes" : "Recipes Dev";
  for (const file of ["plugin.json", ".codex-plugin/plugin.json"]) {
    const value = await readJson(file);
    value.version = version;
    value.name = channel === "stable" ? "recipes" : "recipes-dev";
    const interfaceMetadata = file === "plugin.json" ? value.extensions?.["com.openai"]?.interface : value.interface;
    if (!interfaceMetadata) throw new Error(`Missing plugin interface metadata: ${file}`);
    interfaceMetadata.displayName = displayName;
    await queueJson(file, value);
  }
  for (const file of runtimeFiles) await queue(file, `// Generated by scripts/release.mjs; do not edit manually.\nexport const version = "${version}";\n`);
  return changes;
}

export async function prepareRelease(directory, options) {
  if (!["preview", "write", "check"].includes(options.mode)) throw new Error("Invalid release mode.");
  const changes = await planRelease(directory, options);
  if (options.mode === "check" && changes.length) throw new Error(`Release metadata differs: ${changes.map((change) => change.file).join(", ")}`);
  if (options.mode === "write") for (const { file, after } of changes) await writeFile(join(directory, file), after);
  return changes;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    const options = parseArguments(process.argv.slice(2));
    const changes = await prepareRelease(root, options);
    console.log(`${options.mode}: ${options.channel} ${options.version}; ${changes.length} changed file(s).`);
    for (const { file } of changes) console.log(file);
    if (options.mode === "write") console.log("Next: rebuild bundles, review documentation, and run all release checks. Nothing has been committed or published.");
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
